language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"
# echo test

script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy 
  - docker tag udagram-api-feed chimenim/udagram-api-feed:v1
  - docker tag udagram-api-user chimenim/udagram-api-user:v1
  - docker tag udagram-frontend chimenim/udagram-frontend:v1
  - docker tag udagram-reverseproxy chimenim/reverseproxy:v1
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push chimenim/udagram-api-feed:v1
  - docker push chimenim/udagram-api-user:v1
  - docker push chimenim/udagram-frontend:v1
  - docker push chimenim/reverseproxy:v1